apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster1
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: eks_cluster