apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-course-cluster6
  region: ap-south-1
vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
managedNodeGroups:
  - name: ng-1
    
    instanceType: t3.small
    desiredCapacity: 1
   # privateNetworking: true
    ssh: # use existing EC2 key
      allow: true
      publicKeyName: eks_cluster